name: trail_queue_models
description: Shared models and enums for Trail Queue
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  equatable: ^2.0.7
  latlong2: ^0.9.1

dev_dependencies:
  test: ^1.25.8
