// File generated by FlutterFire CLI — replace with `flutterfire configure`.
// ignore_for_file: lines_longer_than_80_chars

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Placeholder options. Run `flutterfire configure` in apps/client to replace.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: '1:REPLACE:web:REPLACE',
    messagingSenderId: 'REPLACE',
    projectId: 'trail-queue',
    authDomain: 'trail-queue.firebaseapp.com',
    storageBucket: 'trail-queue.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: '1:REPLACE:android:REPLACE',
    messagingSenderId: 'REPLACE',
    projectId: 'trail-queue',
    storageBucket: 'trail-queue.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: '1:REPLACE:ios:REPLACE',
    messagingSenderId: 'REPLACE',
    projectId: 'trail-queue',
    storageBucket: 'trail-queue.appspot.com',
    iosBundleId: 'com.trailqueue.trailQueue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: '1:REPLACE:ios:REPLACE',
    messagingSenderId: 'REPLACE',
    projectId: 'trail-queue',
    storageBucket: 'trail-queue.appspot.com',
    iosBundleId: 'com.trailqueue.trailQueue',
  );
}
